#!/usr/bin/env python
# -*- encoding: utf-8 -*-
# Created on 2017-04-11 10:24:27
# Project: shopDistrict0411
#根据第一个项目中所获得的商户数据，获得该商户对应的经纬度。
#数据结构为：
#商户ID，经度，纬度
from pyspider.libs.base_handler import *
import csv
import re
#from bs4 import BeautifulSoup
class Handler(BaseHandler):
    crawl_config = {
    }

    @every(minutes=24 * 60)
    def on_start(self):
        csvfile = file('/home/xuqiang/DZDP02.csv','rb')
        reader = csv.reader(csvfile)
        for line in reader:
            shopId = line[3]
            url = 'http://www.dianping.com/shop/'+str(shopId)
            self.crawl(url, callback=self.detail_page,fetch_type='js',save={'shopId':shopId})

  
    @config(priority=2)
    def detail_page(self, response):  
        #soup = BeautifulSoup(response.text)  
        imgurl = response.doc('#map > img').attr.src
        #imgurl=soup.find('div',id="map", class_="container").find('img').get('src')    
        latLng=re.findall(r"\d\d.\d+\.?\d*,\d\d\d.\d+\.?\d*",imgurl)[0]
        lat=latLng.split(',')[0]
        lng=latLng.split(',')[1]
        return {
            "shopId": response.save['shopId'],
            "lat": lat,
            "lng": lng        
        }
    

